FROM openjdk:17-alpine
ADD tiny-url-0.0.1-SNAPSHOT.jar /tiny-url.jar 
MAINTAINER VIVI<172031436@qq.com>
# 安装支持的字体 【修改处1】
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN set -xe && apk --no-cache add ttf-dejavu fontconfig
# 设置中文支持 【修改处2】
# setup language 解决中文乱码
ENV  LANG C.UTF-8
EXPOSE 8001
ENTRYPOINT ["java","-jar","/tiny-url.jar"]